# Generated by Django 4.2.5 on 2024-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
