# Generated by Django 4.2.5 on 2024-03-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='portfolio',
        ),
    ]
