# Generated by Django 4.2.5 on 2024-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_trade_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='total_shares',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='total_trades',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='winrate',
            field=models.FloatField(null=True),
        ),
    ]
