# Generated by Django 4.2.5 on 2024-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trader_total_shares_trader_total_trades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='total_Gain',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
