# Generated by Django 4.2.5 on 2024-03-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trade_remove_trader_subscribers_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='is_buy',
        ),
    ]
