# Generated by Django 4.2.5 on 2024-03-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_trade_fee_remove_trade_is_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
