# Generated by Django 4.2.5 on 2024-03-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='premium_price',
        ),
        migrations.AddField(
            model_name='trader',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='myapp.offering'),
        ),
    ]
