# Generated by Django 4.2.5 on 2024-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_trader_premium_price_trader_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='is_trader',
            field=models.BooleanField(default=True),
        ),
    ]
